--insert into BENCHMARK values('bm1','bench1');
--insert into BENCHMARK values('bm2','bench2');
--
--insert into FUND values('fund1','fund1','bm1');
--insert into FUND values('fund2','fund2','bm1');
--insert into FUND values('fund3','fund3','bm2');
drop table if exists FUND
drop table if exists BENCHMARK
drop table if exists benchreturnseries
drop table if exists fundreturnseries

CREATE TABLE BENCHMARK(BENCHMARKCODE VARCHAR(200), BENCHMARKNAME VARCHAR(200)) AS SELECT * FROM CSVREAD('classpath:benchmark.csv')
CREATE TABLE FUND(FUNDCODE VARCHAR(200) PRIMARY KEY, FUNDNAME VARCHAR(200), BENCHMARKCODE VARCHAR(200) ) AS SELECT * FROM CSVREAD('classpath:fund.csv')
CREATE TABLE BENCHRETURNSERIES(ID bigint  , BENCHMARKCODE VARCHAR(200), RETURNDATE DATE, RETURNPER DOUBLE) AS SELECT ID,CODE,FORMATDATETIME(PARSEDATETIME(RETURNDATE ,'dd/MM/yyyy') ,'yyyy-MM-dd'),RETURNPER FROM CSVREAD('classpath:BenchReturnSeries.csv')
CREATE TABLE FUNDRETURNSERIES(ID bigint  , FUNDCODE VARCHAR(200), RETURNDATE DATE, RETURNPER DOUBLE) AS SELECT ID,CODE,FORMATDATETIME(PARSEDATETIME(RETURNDATE ,'dd/MM/yyyy') ,'yyyy-MM-dd'),RETURNPER FROM CSVREAD('classpath:FundReturnSeries.csv')
--CREATE TABLE FUNDRETURNSERIES(FUNDCODE VARCHAR(200), RETURNDATE Date, RETURNPER DOUBLE) AS SELECT   TEMPFUNDRETURNTAB.CODE, FORMATDATETIME(PARSEDATETIME(RDATE ,'dd/MM/yyyy') ,'yyyy-MM-dd') as TEMPFUNDRETURNTAB.RDATE,TEMPFUNDRETURNTAB.RPER FROM TEMPFUNDRETURNTAB